// Production requests use the page's own origin through Nginx.
const base = process.env.NODE_ENV === "production" ? "" : (process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000");
export function token(role: string) { return typeof window === "undefined" ? null : sessionStorage.getItem(`token:${role}`); }
export function logout() { if(typeof window!=="undefined")["viewer","uploader","admin"].forEach(role=>sessionStorage.removeItem(`token:${role}`)); }
export class ApiError extends Error { status:number; detail:unknown; constructor(message:string,status:number,detail:unknown){super(message);this.name="ApiError";this.status=status;this.detail=detail;} }
export async function login(role: "viewer"|"uploader"|"admin", password: string) { const r=await fetch(`${base}/api/auth/${role}-login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})}); if(!r.ok) throw new Error((await r.json()).detail||"密码错误"); const data=await r.json(); ["viewer","uploader","admin"].forEach(name=>sessionStorage.removeItem(`token:${name}`)); sessionStorage.setItem(`token:${role}`,data.access_token); return data; }
export async function api(path:string, options:RequestInit={}, roles:string[]=[]){ const t=roles.map(token).find(Boolean); const headers=new Headers(options.headers); if(t) headers.set("Authorization",`Bearer ${t}`); const started=typeof performance!=="undefined"?performance.now():0; try { const r=await fetch(`${base}${path}`,{...options,headers}); if(!r.ok){const payload=await r.json().catch(()=>({}));if(process.env.NODE_ENV!=="production") console.warn("API request failed",path,r.status);if(r.status===401&&typeof window!=="undefined"){["viewer","uploader","admin"].forEach(role=>sessionStorage.removeItem(`token:${role}`));window.location.assign("/")}const detail=payload.detail;const message=typeof detail === "string" ? detail : (detail?.message || `请求失败 (${r.status})`);throw new ApiError(message,r.status,detail)} if(process.env.NODE_ENV!=="production") console.debug("API request",path,`${Math.round(performance.now()-started)}ms`); return r.json(); } catch(error) { if(process.env.NODE_ENV!=="production") console.error("API request error",path,error); throw error; } }
export function mediaUrl(path:string){return `${base}${path}`}
export async function download(path:string, filename:string, roles:string[]=[]){ const t=roles.map(token).find(Boolean); const headers=new Headers(); if(t) headers.set("Authorization",`Bearer ${t}`); const r=await fetch(`${base}${path}`,{headers}); if(!r.ok) throw new Error((await r.json().catch(()=>({}))).detail||`请求失败 (${r.status})`); const url=URL.createObjectURL(await r.blob()); const link=document.createElement("a"); link.href=url; link.download=filename; link.click(); URL.revokeObjectURL(url); }
